apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  namespace: "minio"
spec:
  template:
    spec:
      initContainers:
      - name: init-container
        image: python:3.8
        # run python command
        command: ["python", "/scripts/script.py"]
        volumeMounts:
        - name: script-volume
          mountPath: /scripts
      volumes:
      - name: script-volume
        configMap:
          name: python-script 
