apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  namespace: "minio"
spec:
  template:
    spec:
      containers:
      - name: python-script-container
        image: jbolivarlt/python_kubernetes
        imagePullPolicy: Always
        command: ["python", "/scripts/script.py"]
        volumeMounts:
        - name: script-volume
          mountPath: /scripts
      volumes:
      - name: script-volume
        configMap:
          name: python-script
       
